### ISSUE TITLE
Feature suggestion: Select Python interpreter directly from this extension

### ISSUE THREAD

**Issue by bland328** [DonJayamanne/vscode-python-manager#19]
Thanks for this extension! If there are not already plans to do so, I'd love to be able to change the current Python interpreter (that is, automatically issue the `Python: Select Interpreter` command) directly from the root of the list of venvs shown by `vscode-python-manager`.

It would be very slick to be able to accomplish that by way of a right-click context menu, or additional button next to the `Open in Terminal` button, or whatever interface might make the most sense.

**Comment by mcarans** [comment]
@DonJayamanne This extension is a great idea. I have taken a look a VSCode a few times, but keep going back to PyCharm because its interpreter handling is so good. Being able to both create and select interpreters in this extension would be a huge improvement to VSCode's Python support.

**Comment by DonJayamanne** [comment]
ill be working on this feature soon

**Comment by DonJayamanne** [comment]
This has been completed
