### ISSUE TITLE
Conda Enviroment is not created

### ISSUE THREAD

**Issue by nstein-gpjoule** [DonJayamanne/vscode-python-manager#49]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

**Expected:**
When + is clicked a new conda enviroment should be created. 

**Actual:**
There are two notifications in the right corner poping up and closing fastly, afterwards there is no new conda env or error message

## Steps to reproduce:

1. Click on + follow the dialogs

# Diagnostic data

-   Python version: 3.9.13
-   Conda version: 22.11.1
-   Windows 10 Pro 22H2
-   Type of virtual environment used: Conda
-   Value of the `python.languageServer` setting: Default

Extension version: 1.0.4
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.08GB free)|
|Process Argv|--crash-reporter-id efa07db7-a6a1-49bd-bc99-4fcc63568dd1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by flight505** [comment]
+1

**Comment by liwh011** [comment]
i solved the problem by following steps. You can try to run `conda activate xxx` in powershell and if your terminal prompts `Your shell has not been properly configured` , this may help you.
1. run `conda init powershell` in powershell(admin mode)
2. run `set-executionpolicy remotesigned` to allow powershell to execute scripts before it start up

**Comment by andycjw** [comment]
> i solved the problem by following steps. You can try to run `conda activate xxx` in powershell and if your terminal prompts `Your shell has not been properly configured` , this may help you.
> 
> 1. run `conda init powershell` in powershell(admin mode)
> 2. run `set-executionpolicy remotesigned` to allow powershell to execute scripts before it start up

I already did this, and can activate the 'base' env without any problem, but the create by clicking '+' in the extension is still not working for me, but manual create with 'conda create' works, I need help debugging this.

**Comment by Xummer1998** [comment]
hello, have you ever solved this problem? I met the same mistake.

**Comment by Lightup1** [comment]
+1, `python: Create ...` command in vscode is also not working if I choose to use conda to create env.

**Comment by DonJayamanne** [comment]
> 1, python: Create ... command in vscode is also not working if I choose to use conda to create env.

looks like an upstream issue in the python extension
Please could up file an issued on the microsoft python extension repo
