### ISSUE TITLE
Cross-platform environment setup

### ISSUE THREAD

**Issue by superrune** [DonJayamanne/vscode-python-manager#83]
Hi,

I have both a Windows and a macOS workstation that I switch between, and I need to find an easy way to keep my Python workspace cross-compatible.  If I create a virtual environment in one OS, the extension want to overwrite or delete the virtual environment when I jump over to the other OS.

Is there a way to have the virtual environments have different names in different OS'es using this extension? Or is there another way to make a project folder cross-platform compatible with this extension?

Thanks for any help!

**Comment by DonJayamanne** [comment]
are you committing the python environment into a git repo or the like and making it part of your project?

**Comment by superrune** [comment]
Hi! I am using Dropbox only, and no repo of any kind.

**Comment by DonJayamanne** [comment]
> using Dropbox only, and no repo of any 

unfortunately this isn’t supported and not something I plan on supporting either
You might want to file an issue against the python extension repo

I haven’t heard of anyone doing this, then again I guess there’s no reason it can’t work
Interesting setup

**Comment by superrune** [comment]
Thanks for replying. I think it can be fixed if a user was able to change the name of the virtual environment. The Python extension repo guys sent me here :)

I'll see if I can find a workaround.

**Comment by DonJayamanne** [comment]
> The Python extension repo guys sent me here, actually :)

THanks, Please could you share that link/issue.
I'd like to have a look, as this seems to be more of a Python extension issue than something that needs to be solved by the Python Manager.

**Comment by superrune** [comment]
Of course, here is the link:

https://github.com/microsoft/vscode-python/discussions/22716#discussioncomment-8077325
